# Generated by Django 5.1.4 on 2025-01-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('P', 'Planta'), ('T', 'Tierra'), ('L', 'Lagartija'), ('E', 'Eléctrico'), ('F', 'Fuego'), ('A', 'Agua')], max_length=30),
        ),
    ]
