# Generated by Django 4.2.11 on 2025-01-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('A', 'Agua'), ('T', 'Tierra'), ('F', 'Fuego'), ('P', 'Planta'), ('E', 'Eléctrico'), ('L', 'Lagartija')], max_length=30),
        ),
    ]
