# Generated by Django 5.1.4 on 2025-01-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('P', 'Planta'), ('E', 'Eléctrico'), ('A', 'Agua'), ('T', 'Tierra'), ('L', 'Lagartija'), ('F', 'Fuego')], max_length=30),
        ),
    ]
